const router = require('express').Router();
const controller = require('../controllers/usuariosController');
const { authenticate, requireAdmin } = require('../middleware/auth');
router.use(authenticate, requireAdmin);
router.get('/', controller.index);
router.get('/:id', controller.show);
router.post('/', controller.create);
router.put('/:id', controller.update);
router.delete('/:id', controller.remove);
module.exports = router;